In [2]:
import pandas as pd

df = pd.read_csv("../data/application_train.csv")
df

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,100002,1,Cash loans,M,N,Y,0,202500.0,406597.5,24700.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
1,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
2,100004,0,Revolving loans,M,Y,Y,0,67500.0,135000.0,6750.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3,100006,0,Cash loans,F,N,Y,0,135000.0,312682.5,29686.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4,100007,0,Cash loans,M,N,Y,0,121500.0,513000.0,21865.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
307506,456251,0,Cash loans,M,N,N,0,157500.0,254700.0,27558.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
307507,456252,0,Cash loans,F,N,Y,0,72000.0,269550.0,12001.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
307508,456253,0,Cash loans,F,N,Y,0,153000.0,677664.0,29979.0,...,0,0,0,0,1.0,0.0,0.0,1.0,0.0,1.0
307509,456254,1,Cash loans,F,N,Y,0,171000.0,370107.0,20205.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
307510,456255,0,Cash loans,F,N,N,0,157500.0,675000.0,49117.5,...,0,0,0,0,0.0,0.0,0.0,2.0,0.0,1.0

In [3]:
chunk_size = 10
chunks = {f"Cols {i+1}-{i+chunk_size}": df.columns[i:i+chunk_size].tolist() 
          for i in range(0, len(df.columns), chunk_size)}

# Fills missing values automatically if the last chunk is smaller
grid_df = pd.DataFrame.from_dict(chunks, orient='index').transpose().fillna("")
display(grid_df)

,Cols 1-10,Cols 11-20,Cols 21-30,Cols 31-40,Cols 41-50,Cols 51-60,Cols 61-70,Cols 71-80,Cols 81-90,Cols 91-100,Cols 101-110,Cols 111-120,Cols 121-130
0,SK_ID_CURR,AMT_GOODS_PRICE,DAYS_ID_PUBLISH,REGION_RATING_CLIENT,ORGANIZATION_TYPE,ENTRANCES_AVG,YEARS_BEGINEXPLUATATION_MODE,NONLIVINGAPARTMENTS_MODE,FLOORSMIN_MEDI,EMERGENCYSTATE_MODE,FLAG_DOCUMENT_6,FLAG_DOCUMENT_16,AMT_REQ_CREDIT_BUREAU_QRT
1,TARGET,NAME_TYPE_SUITE,OWN_CAR_AGE,REGION_RATING_CLIENT_W_CITY,EXT_SOURCE_1,FLOORSMAX_AVG,YEARS_BUILD_MODE,NONLIVINGAREA_MODE,LANDAREA_MEDI,OBS_30_CNT_SOCIAL_CIRCLE,FLAG_DOCUMENT_7,FLAG_DOCUMENT_17,AMT_REQ_CREDIT_BUREAU_YEAR
2,NAME_CONTRACT_TYPE,NAME_INCOME_TYPE,FLAG_MOBIL,WEEKDAY_APPR_PROCESS_START,EXT_SOURCE_2,FLOORSMIN_AVG,COMMONAREA_MODE,APARTMENTS_MEDI,LIVINGAPARTMENTS_MEDI,DEF_30_CNT_SOCIAL_CIRCLE,FLAG_DOCUMENT_8,FLAG_DOCUMENT_18,
3,CODE_GENDER,NAME_EDUCATION_TYPE,FLAG_EMP_PHONE,HOUR_APPR_PROCESS_START,EXT_SOURCE_3,LANDAREA_AVG,ELEVATORS_MODE,BASEMENTAREA_MEDI,LIVINGAREA_MEDI,OBS_60_CNT_SOCIAL_CIRCLE,FLAG_DOCUMENT_9,FLAG_DOCUMENT_19,
4,FLAG_OWN_CAR,NAME_FAMILY_STATUS,FLAG_WORK_PHONE,REG_REGION_NOT_LIVE_REGION,APARTMENTS_AVG,LIVINGAPARTMENTS_AVG,ENTRANCES_MODE,YEARS_BEGINEXPLUATATION_MEDI,NONLIVINGAPARTMENTS_MEDI,DEF_60_CNT_SOCIAL_CIRCLE,FLAG_DOCUMENT_10,FLAG_DOCUMENT_20,
5,FLAG_OWN_REALTY,NAME_HOUSING_TYPE,FLAG_CONT_MOBILE,REG_REGION_NOT_WORK_REGION,BASEMENTAREA_AVG,LIVINGAREA_AVG,FLOORSMAX_MODE,YEARS_BUILD_MEDI,NONLIVINGAREA_MEDI,DAYS_LAST_PHONE_CHANGE,FLAG_DOCUMENT_11,FLAG_DOCUMENT_21,
6,CNT_CHILDREN,REGION_POPULATION_RELATIVE,FLAG_PHONE,LIVE_REGION_NOT_WORK_REGION,YEARS_BEGINEXPLUATATION_AVG,NONLIVINGAPARTMENTS_AVG,FLOORSMIN_MODE,COMMONAREA_MEDI,FONDKAPREMONT_MODE,FLAG_DOCUMENT_2,FLAG_DOCUMENT_12,AMT_REQ_CREDIT_BUREAU_HOUR,
7,AMT_INCOME_TOTAL,DAYS_BIRTH,FLAG_EMAIL,REG_CITY_NOT_LIVE_CITY,YEARS_BUILD_AVG,NONLIVINGAREA_AVG,LANDAREA_MODE,ELEVATORS_MEDI,HOUSETYPE_MODE,FLAG_DOCUMENT_3,FLAG_DOCUMENT_13,AMT_REQ_CREDIT_BUREAU_DAY,
8,AMT_CREDIT,DAYS_EMPLOYED,OCCUPATION_TYPE,REG_CITY_NOT_WORK_CITY,COMMONAREA_AVG,APARTMENTS_MODE,LIVINGAPARTMENTS_MODE,ENTRANCES_MEDI,TOTALAREA_MODE,FLAG_DOCUMENT_4,FLAG_DOCUMENT_14,AMT_REQ_CREDIT_BUREAU_WEEK,
9,AMT_ANNUITY,DAYS_REGISTRATION,CNT_FAM_MEMBERS,LIVE_CITY_NOT_WORK_CITY,ELEVATORS_AVG,BASEMENTAREA_MODE,LIVINGAREA_MODE,FLOORSMAX_MEDI,WALLSMATERIAL_MODE,FLAG_DOCUMENT_5,FLAG_DOCUMENT_15,AMT_REQ_CREDIT_BUREAU_MON,

In [4]:
# df[f"FLAG_OWN_CAR"].isna().sum()
print(df[f"AMT_CREDIT"].min())
df[f"FLAG_OWN_CAR"].isna().sum()

45000.0

np.int64(0)

In [12]:
df["NAME_HOUSING_TYPE"].value_counts()

NAME_HOUSING_TYPE
House / apartment      272868
With parents            14840
Municipal apartment     11183
Rented apartment         4881
Office apartment         2617
Co-op apartment          1122
Name: count, dtype: int64

In [13]:
df["NAME_EDUCATION_TYPE"].value_counts()

NAME_EDUCATION_TYPE
Secondary / secondary special    218391
Higher education                  74863
Incomplete higher                 10277
Lower secondary                    3816
Academic degree                     164
Name: count, dtype: int64

In [9]:
df["NAME_INCOME_TYPE"].value_counts()

NAME_INCOME_TYPE
Working                 158774
Commercial associate     71617
Pensioner                55362
State servant            21703
Unemployed                  22
Student                     18
Businessman                 10
Maternity leave              5
Name: count, dtype: int64

In [ ]:
pd.crosstab(df["FLAG_OWN_CAR"],df["OWN_CAR_AGE"].isna(),normalize="index")

OWN_CAR_AGE      False     True
FLAG_OWN_CAR
N             0.000000  1.000000
Y             0.999952  0.000048

In [ ]:
df["CREDIT_INCOME_RATIO"] = (df["AMT_CREDIT"] / df["AMT_INCOME_TOTAL"])
df

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR,CREDIT_INCOME_RATIO
0,100002,1,Cash loans,M,N,Y,0,202500.0,406597.5,24700.5,...,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0,2.007889
1,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,4.790750
2,100004,0,Revolving loans,M,Y,Y,0,67500.0,135000.0,6750.0,...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,2.000000
3,100006,0,Cash loans,F,N,Y,0,135000.0,312682.5,29686.5,...,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,2.316167
4,100007,0,Cash loans,M,N,Y,0,121500.0,513000.0,21865.5,...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,4.222222
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
307506,456251,0,Cash loans,M,N,N,0,157500.0,254700.0,27558.0,...,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,1.617143
307507,456252,0,Cash loans,F,N,Y,0,72000.0,269550.0,12001.5,...,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,3.743750
307508,456253,0,Cash loans,F,N,Y,0,153000.0,677664.0,29979.0,...,0,0,0,1.0,0.0,0.0,1.0,0.0,1.0,4.429176
307509,456254,1,Cash loans,F,N,Y,0,171000.0,370107.0,20205.0,...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,2.164368
307510,456255,0,Cash loans,F,N,N,0,157500.0,675000.0,49117.5,...,0,0,0,0.0,0.0,0.0,2.0,0.0,1.0,4.285714

In [ ]:
missing_pct = (df.isna().mean() * 100).loc[lambda x : x> 0].sort_values(ascending=False)

print(missing_pct.to_string())

COMMONAREA_MEDI                 69.872297
COMMONAREA_MODE                 69.872297
COMMONAREA_AVG                  69.872297
NONLIVINGAPARTMENTS_MODE        69.432963
NONLIVINGAPARTMENTS_MEDI        69.432963
NONLIVINGAPARTMENTS_AVG         69.432963
FONDKAPREMONT_MODE              68.386172
LIVINGAPARTMENTS_AVG            68.354953
LIVINGAPARTMENTS_MEDI           68.354953
LIVINGAPARTMENTS_MODE           68.354953
FLOORSMIN_MEDI                  67.848630
FLOORSMIN_MODE                  67.848630
FLOORSMIN_AVG                   67.848630
YEARS_BUILD_MODE                66.497784
YEARS_BUILD_MEDI                66.497784
YEARS_BUILD_AVG                 66.497784
OWN_CAR_AGE                     65.990810
LANDAREA_AVG                    59.376738
LANDAREA_MEDI                   59.376738
LANDAREA_MODE                   59.376738
BASEMENTAREA_MODE               58.515956
BASEMENTAREA_MEDI               58.515956
BASEMENTAREA_AVG                58.515956
EXT_SOURCE_1                    56.381073
NONLIVINGAREA_MEDI              55.179164
NONLIVINGAREA_AVG               55.179164
NONLIVINGAREA_MODE              55.179164
ELEVATORS_MEDI                  53.295980
ELEVATORS_MODE                  53.295980
ELEVATORS_AVG                   53.295980
WALLSMATERIAL_MODE              50.840783
APARTMENTS_AVG                  50.749729
APARTMENTS_MEDI                 50.749729
APARTMENTS_MODE                 50.749729
ENTRANCES_MODE                  50.348768
ENTRANCES_MEDI                  50.348768
ENTRANCES_AVG                   50.348768
LIVINGAREA_AVG                  50.193326
LIVINGAREA_MODE                 50.193326
LIVINGAREA_MEDI                 50.193326
HOUSETYPE_MODE                  50.176091
FLOORSMAX_AVG                   49.760822
FLOORSMAX_MEDI                  49.760822
FLOORSMAX_MODE                  49.760822
YEARS_BEGINEXPLUATATION_MODE    48.781019
YEARS_BEGINEXPLUATATION_MEDI    48.781019
YEARS_BEGINEXPLUATATION_AVG     48.781019
TOTALAREA_MODE                  48.268517
EMERGENCYSTATE_MODE             47.398304
OCCUPATION_TYPE                 31.345545
EXT_SOURCE_3                    19.825307
AMT_REQ_CREDIT_BUREAU_WEEK      13.501631
AMT_REQ_CREDIT_BUREAU_MON       13.501631
AMT_REQ_CREDIT_BUREAU_HOUR      13.501631
AMT_REQ_CREDIT_BUREAU_YEAR      13.501631
AMT_REQ_CREDIT_BUREAU_QRT       13.501631
AMT_REQ_CREDIT_BUREAU_DAY       13.501631
NAME_TYPE_SUITE                  0.420148
DEF_30_CNT_SOCIAL_CIRCLE         0.332021
DEF_60_CNT_SOCIAL_CIRCLE         0.332021
OBS_30_CNT_SOCIAL_CIRCLE         0.332021
OBS_60_CNT_SOCIAL_CIRCLE         0.332021
EXT_SOURCE_2                     0.214626
AMT_GOODS_PRICE                  0.090403
AMT_ANNUITY                      0.003902
CNT_FAM_MEMBERS                  0.000650
DAYS_LAST_PHONE_CHANGE           0.000325