In [1]:
import pandas as pd

df = pd.read_csv("../data/bureau.csv")
df

,SK_ID_CURR,SK_ID_BUREAU,CREDIT_ACTIVE,CREDIT_CURRENCY,DAYS_CREDIT,CREDIT_DAY_OVERDUE,DAYS_CREDIT_ENDDATE,DAYS_ENDDATE_FACT,AMT_CREDIT_MAX_OVERDUE,CNT_CREDIT_PROLONG,AMT_CREDIT_SUM,AMT_CREDIT_SUM_DEBT,AMT_CREDIT_SUM_LIMIT,AMT_CREDIT_SUM_OVERDUE,CREDIT_TYPE,DAYS_CREDIT_UPDATE,AMT_ANNUITY
0,215354,5714462,Closed,currency 1,-497,0,-153.0,-153.0,NaN,0,91323.00,0.0,NaN,0.0,Consumer credit,-131,NaN
1,215354,5714463,Active,currency 1,-208,0,1075.0,NaN,NaN,0,225000.00,171342.0,NaN,0.0,Credit card,-20,NaN
2,215354,5714464,Active,currency 1,-203,0,528.0,NaN,NaN,0,464323.50,NaN,NaN,0.0,Consumer credit,-16,NaN
3,215354,5714465,Active,currency 1,-203,0,NaN,NaN,NaN,0,90000.00,NaN,NaN,0.0,Credit card,-16,NaN
4,215354,5714466,Active,currency 1,-629,0,1197.0,NaN,77674.5,0,2700000.00,NaN,NaN,0.0,Consumer credit,-21,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1716423,259355,5057750,Active,currency 1,-44,0,-30.0,NaN,0.0,0,11250.00,11250.0,0.0,0.0,Microloan,-19,NaN
1716424,100044,5057754,Closed,currency 1,-2648,0,-2433.0,-2493.0,5476.5,0,38130.84,0.0,0.0,0.0,Consumer credit,-2493,NaN
1716425,100044,5057762,Closed,currency 1,-1809,0,-1628.0,-970.0,NaN,0,15570.00,NaN,NaN,0.0,Consumer credit,-967,NaN
1716426,246829,5057770,Closed,currency 1,-1878,0,-1513.0,-1513.0,NaN,0,36000.00,0.0,0.0,0.0,Consumer credit,-1508,NaN
1716427,246829,5057778,Closed,currency 1,-463,0,NaN,-387.0,NaN,0,22500.00,0.0,NaN,0.0,Microloan,-387,NaN

In [2]:
print(df["AMT_CREDIT_SUM"].max())
# df["CREDIT_DAY_OVERDUE"].value_counts()

585000000.0

In [12]:
df1 = pd.read_csv("../data/previous_application.csv")
df1
prev_app_count = df1.groupby("SK_ID_CURR")["SK_ID_PREV"].count()
# for col in df1.columns:
#     print(col)
df1["AMT_APPLICATION"].min()

np.float64(0.0)

In [14]:
df1["CREDIT_APPLICATION_RATIO"] = (
        df1["AMT_CREDIT"]
        / df1["AMT_APPLICATION"].replace(0, pd.NA)
    )

ratio_features = (
        df1.groupby("SK_ID_CURR")["CREDIT_APPLICATION_RATIO"]
        .agg(["mean", "max", "min"])
    )
ratio_features

                mean       max       min
SK_ID_CURR
100001      0.957782  0.957782  0.957782
100002           1.0       1.0       1.0
100003      1.057664   1.15098  0.989013
100004      0.828021  0.828021  0.828021
100005       0.89995   0.89995   0.89995
...              ...       ...       ...
456251           1.0       1.0       1.0
456252      0.986561  0.986561  0.986561
456253      0.831397  0.944436  0.718359
456254       1.12205  1.138491  1.105608
456255      1.115884     1.396       1.0

[338857 rows x 3 columns]

In [ ]:
status_counts = pd.crosstab(
        df1["SK_ID_CURR"],
        df1["NAME_CONTRACT_STATUS"]
    )
status_counts

NAME_CONTRACT_STATUS  Approved  Canceled  Refused  Unused offer
SK_ID_CURR
100001                       1         0        0             0
100002                       1         0        0             0
100003                       3         0        0             0
100004                       1         0        0             0
100005                       1         1        0             0
...                        ...       ...      ...           ...
456251                       1         0        0             0
456252                       1         0        0             0
456253                       2         0        0             0
456254                       2         0        0             0
456255                       6         0        2             0

[338857 rows x 4 columns]

In [15]:
df1["NFLAG_INSURED_ON_APPROVAL"]

0          0.0
1          1.0
2          1.0
3          1.0
4          NaN
          ...
1670209    0.0
1670210    0.0
1670211    0.0
1670212    1.0
1670213    0.0
Name: NFLAG_INSURED_ON_APPROVAL, Length: 1670214, dtype: float64

In [18]:
df2 = pd.read_csv("../data/installments_payments.csv")
print(df2.shape)
df2.columns.tolist()

(13605401, 8)

['SK_ID_PREV',
 'SK_ID_CURR',
 'NUM_INSTALMENT_VERSION',
 'NUM_INSTALMENT_NUMBER',
 'DAYS_INSTALMENT',
 'DAYS_ENTRY_PAYMENT',
 'AMT_INSTALMENT',
 'AMT_PAYMENT']

In [28]:
df2["NUM_INSTALMENT_VERSION"]

0           1.0
1           0.0
2           2.0
3           1.0
4           1.0
           ...
13605396    0.0
13605397    0.0
13605398    0.0
13605399    0.0
13605400    1.0
Name: NUM_INSTALMENT_VERSION, Length: 13605401, dtype: float64