In [7]:
import pandas as pd

df = pd.read_csv("../data/application_train.csv")
# for col in df.columns:
#     print(col)
df

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,100002,1,Cash loans,M,N,Y,0,202500.0,406597.5,24700.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
1,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
2,100004,0,Revolving loans,M,Y,Y,0,67500.0,135000.0,6750.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3,100006,0,Cash loans,F,N,Y,0,135000.0,312682.5,29686.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4,100007,0,Cash loans,M,N,Y,0,121500.0,513000.0,21865.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
307506,456251,0,Cash loans,M,N,N,0,157500.0,254700.0,27558.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
307507,456252,0,Cash loans,F,N,Y,0,72000.0,269550.0,12001.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
307508,456253,0,Cash loans,F,N,Y,0,153000.0,677664.0,29979.0,...,0,0,0,0,1.0,0.0,0.0,1.0,0.0,1.0
307509,456254,1,Cash loans,F,N,Y,0,171000.0,370107.0,20205.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
307510,456255,0,Cash loans,F,N,N,0,157500.0,675000.0,49117.5,...,0,0,0,0,0.0,0.0,0.0,2.0,0.0,1.0

In [24]:
df[df["TARGET"]==1]["SK_ID_CURR"].head(30)
# df["CREDIT_DAY_OVERDUE"].value_counts()

0      100002
26     100031
40     100047
42     100049
81     100096
94     100112
110    100130
138    100160
154    100181
163    100192
180    100209
184    100214
211    100246
235    100273
242    100282
246    100286
255    100295
260    100300
261    100301
283    100326
291    100336
344    100396
348    100401
368    100424
381    100439
389    100452
408    100472
413    100477
419    100485
424    100490
Name: SK_ID_CURR, dtype: int64

In [9]:
df1 = pd.read_csv("../data/previous_application.csv")
prev_app_count = df1.groupby("SK_ID_CURR")["SK_ID_PREV"].count()
df1
# for col in df1.columns:
#     print(col)
df1["AMT_APPLICATION"].min()

np.float64(0.0)

In [10]:
import numpy as np
df1["CREDIT_APPLICATION_RATIO"] = (
        df1["AMT_CREDIT"]
        / df1["AMT_APPLICATION"].replace(0, np.nan)
    )

ratio_features = (
        df1.groupby("SK_ID_CURR")["CREDIT_APPLICATION_RATIO"]
        .agg(["mean", "max", "min"])
    )
ratio_features

                mean       max       min
SK_ID_CURR
100001      0.957782  0.957782  0.957782
100002      1.000000  1.000000  1.000000
100003      1.057664  1.150980  0.989013
100004      0.828021  0.828021  0.828021
100005      0.899950  0.899950  0.899950
...              ...       ...       ...
456251      1.000000  1.000000  1.000000
456252      0.986561  0.986561  0.986561
456253      0.831397  0.944436  0.718359
456254      1.122050  1.138491  1.105608
456255      1.115884  1.396000  1.000000

[338857 rows x 3 columns]

In [11]:
status_counts = pd.crosstab(
        df1["SK_ID_CURR"],
        df1["NAME_CONTRACT_STATUS"]
    )
status_counts

NAME_CONTRACT_STATUS  Approved  Canceled  Refused  Unused offer
SK_ID_CURR
100001                       1         0        0             0
100002                       1         0        0             0
100003                       3         0        0             0
100004                       1         0        0             0
100005                       1         1        0             0
...                        ...       ...      ...           ...
456251                       1         0        0             0
456252                       1         0        0             0
456253                       2         0        0             0
456254                       2         0        0             0
456255                       6         0        2             0

[338857 rows x 4 columns]

In [12]:
df1["NFLAG_INSURED_ON_APPROVAL"]

0          0.0
1          1.0
2          1.0
3          1.0
4          NaN
          ...
1670209    0.0
1670210    0.0
1670211    0.0
1670212    1.0
1670213    0.0
Name: NFLAG_INSURED_ON_APPROVAL, Length: 1670214, dtype: float64

In [13]:
df2 = pd.read_csv("../data/installments_payments.csv")
print(df2.shape)
df2.columns.tolist()

(13605401, 8)

['SK_ID_PREV',
 'SK_ID_CURR',
 'NUM_INSTALMENT_VERSION',
 'NUM_INSTALMENT_NUMBER',
 'DAYS_INSTALMENT',
 'DAYS_ENTRY_PAYMENT',
 'AMT_INSTALMENT',
 'AMT_PAYMENT']

In [14]:
df2["NUM_INSTALMENT_VERSION"]

0           1.0
1           0.0
2           2.0
3           1.0
4           1.0
           ...
13605396    0.0
13605397    0.0
13605398    0.0
13605399    0.0
13605400    1.0
Name: NUM_INSTALMENT_VERSION, Length: 13605401, dtype: float64

In [15]:
df2 = pd.read_csv("../data/application_test.csv")
df2
for col in df2.columns:
    print(col)

SK_ID_CURR
NAME_CONTRACT_TYPE
CODE_GENDER
FLAG_OWN_CAR
FLAG_OWN_REALTY
CNT_CHILDREN
AMT_INCOME_TOTAL
AMT_CREDIT
AMT_ANNUITY
AMT_GOODS_PRICE
NAME_TYPE_SUITE
NAME_INCOME_TYPE
NAME_EDUCATION_TYPE
NAME_FAMILY_STATUS
NAME_HOUSING_TYPE
REGION_POPULATION_RELATIVE
DAYS_BIRTH
DAYS_EMPLOYED
DAYS_REGISTRATION
DAYS_ID_PUBLISH
OWN_CAR_AGE
FLAG_MOBIL
FLAG_EMP_PHONE
FLAG_WORK_PHONE
FLAG_CONT_MOBILE
FLAG_PHONE
FLAG_EMAIL
OCCUPATION_TYPE
CNT_FAM_MEMBERS
REGION_RATING_CLIENT
REGION_RATING_CLIENT_W_CITY
WEEKDAY_APPR_PROCESS_START
HOUR_APPR_PROCESS_START
REG_REGION_NOT_LIVE_REGION
REG_REGION_NOT_WORK_REGION
LIVE_REGION_NOT_WORK_REGION
REG_CITY_NOT_LIVE_CITY
REG_CITY_NOT_WORK_CITY
LIVE_CITY_NOT_WORK_CITY
ORGANIZATION_TYPE
EXT_SOURCE_1
EXT_SOURCE_2
EXT_SOURCE_3
APARTMENTS_AVG
BASEMENTAREA_AVG
YEARS_BEGINEXPLUATATION_AVG
YEARS_BUILD_AVG
COMMONAREA_AVG
ELEVATORS_AVG
ENTRANCES_AVG
FLOORSMAX_AVG
FLOORSMIN_AVG
LANDAREA_AVG
LIVINGAPARTMENTS_AVG
LIVINGAREA_AVG
NONLIVINGAPARTMENTS_AVG
NONLIVINGAREA_AVG
APARTMENTS_MODE
BASEMENTAREA_MODE
YEARS_BEGINEXPLUATATION_MODE
YEARS_BUILD_MODE
COMMONAREA_MODE
ELEVATORS_MODE
ENTRANCES_MODE
FLOORSMAX_MODE
FLOORSMIN_MODE
LANDAREA_MODE
LIVINGAPARTMENTS_MODE
LIVINGAREA_MODE
NONLIVINGAPARTMENTS_MODE
NONLIVINGAREA_MODE
APARTMENTS_MEDI
BASEMENTAREA_MEDI
YEARS_BEGINEXPLUATATION_MEDI
YEARS_BUILD_MEDI
COMMONAREA_MEDI
ELEVATORS_MEDI
ENTRANCES_MEDI
FLOORSMAX_MEDI
FLOORSMIN_MEDI
LANDAREA_MEDI
LIVINGAPARTMENTS_MEDI
LIVINGAREA_MEDI
NONLIVINGAPARTMENTS_MEDI
NONLIVINGAREA_MEDI
FONDKAPREMONT_MODE
HOUSETYPE_MODE
TOTALAREA_MODE
WALLSMATERIAL_MODE
EMERGENCYSTATE_MODE
OBS_30_CNT_SOCIAL_CIRCLE
DEF_30_CNT_SOCIAL_CIRCLE
OBS_60_CNT_SOCIAL_CIRCLE
DEF_60_CNT_SOCIAL_CIRCLE
DAYS_LAST_PHONE_CHANGE
FLAG_DOCUMENT_2
FLAG_DOCUMENT_3
FLAG_DOCUMENT_4
FLAG_DOCUMENT_5
FLAG_DOCUMENT_6
FLAG_DOCUMENT_7
FLAG_DOCUMENT_8
FLAG_DOCUMENT_9
FLAG_DOCUMENT_10
FLAG_DOCUMENT_11
FLAG_DOCUMENT_12
FLAG_DOCUMENT_13
FLAG_DOCUMENT_14
FLAG_DOCUMENT_15
FLAG_DOCUMENT_16
FLAG_DOCUMENT_17
FLAG_DOCUMENT_18
FLAG_DOCUMENT_19
FLAG_DOCUMENT_20
FLAG_DOCUMENT_21
AMT_REQ_CREDIT_BUREAU_HOUR
AMT_REQ_CREDIT_BUREAU_DAY
AMT_REQ_CREDIT_BUREAU_WEEK
AMT_REQ_CREDIT_BUREAU_MON
AMT_REQ_CREDIT_BUREAU_QRT
AMT_REQ_CREDIT_BUREAU_YEAR